### ISSUE TITLE
Hello, do you still support  Sibrary G6

### ISSUE THREAD

**Issue by zhenruyan** [S-trace/eView#5]
and is this software or firmware?

**Comment by S-trace** [comment]
Hello. 
I don't have a working Sibrary G6 device (have 2 devices, but one have broken screen, and another one have broken board and does not work at all).
But i'm have Kobo Aura H2O reader and ported eView to this device (have some power management and archive-related issues yet, but already can read non-archived manga)

**Comment by zhenruyan** [comment]
Thank you for your reply, I can compile it, but how should I install it on my device?

**Comment by S-trace** [comment]
You should build installer using "make installer" command, copy it to the device find the installer in file manager and then start it

**Comment by zhenruyan** [comment]
Thanks, so is it software or firmware? Do you support Chinese content? Is it easy to rollback the version after installation?

**Comment by S-trace** [comment]
This is software.
eView can be started on leagacy Sibrary G6 GTK-based firmware directly, or on new Sibrary G6 Qt-based firmware using GTK-parts package (must be installed only once).
The old GTK-based firmware looks like this: https://www.evgeniystepanov.ru/images-elektronnye-knigi/sibrary-g6.jpg
Or like this: https://cdn.alza.cz/ImgW.ashx?fd=f3&cd=SBR001
The new Qt-based firmware looks like this: https://mobidevices.ru/images/2012/12/4146wb.jpg
I do not support Chinese locale because I don't know Chinese. But eView have Russian and English translation. You can try to translate eView to Chinese if you want.
eView of course can read manga or comics in any language (but I did not tested is the localized filenames supported well).
You can reflash your firmware to get rid of eView if you want, but it replaces not-so-useful parts of firmware (user manual page of Start menu).

**Comment by zhenruyan** [comment]
OK, I see, thanks for your answer, I will try to add Chinese support
